Repository nicolegooden/indecision-maker, pull requests merged in 2020-11, with the labels that each got.

#43 Display activities om
  src/Components/App/App.js
  src/Components/App/App.scss
  src/Components/BrowsePage/BrowsePage.js
  src/Components/BrowsePage/BrowsePage.scss
  src/Components/BrowsePage/BrowsePage.test.js
  src/Components/Footer/Footer.js
  src/Components/Footer/Footer.scss
  src/Components/HomePage/Homepage.js
  src/Components/HomePage/Homepage.scss
  src/apiCalls.js
  src/styles/_variables.scss
Labels: Styling, extension, iteration 3

#42 Activity components ng
  src/Components/App/App.js
  src/Components/BoardGame/BoardGame.js
  src/Components/CardGame/CardGame.js
  src/Components/Form/Form.js
  src/Components/Form/questions.js
  src/Components/Movie/Movie.js
  src/Components/Music/Music.js
  src/Components/Podcast/Podcast.js
Labels: documentation

#49 Create result and detail page components om
  src/Components/App/App.js
  src/Components/DetailPage/DetailsPage.js
  src/Components/DetailPage/DetailsPage.scss
  src/Components/DetailPage/DetaislPage.test.js
  src/Components/HomePage/Homepage.js
  src/Components/HomePage/Homepage.scss
  src/Components/ResultPage/ResultPage.js
  src/Components/ResultPage/ResultPage.scss
  src/Components/ResultPage/ResultPage.test.js
  src/styles/_variables.scss
Labels: MVP, Styling, iteration 3

#51 Determine random activity based on user selections
  src/Components/App/App.js
  src/Components/Form/Form.js
Labels: Front end, MVP, iteration 3

#62 Initial tests bd
  src/Components/App/App.test.js
  src/Components/BrowsePage/BrowsePage.js
  src/Components/BrowsePage/BrowsePage.test.js
  src/Components/HomePage/Homepage.test.js
  src/apiCalls.js
Labels: Back end, MVP, Testing

#61 Edit readme om
  README.md
Labels: Refactor needed, documentation

#69 Fix bug with displaying empty suggetsions
  src/Components/App/App.js
  src/Components/ResultPage/ResultPage.js
  src/Components/ResultPage/ResultPage.test.js
Labels: bug

#70 Fix failing test om
  src/Components/ActivityCards/ActivityCards.test.js
  src/Components/DetailPage/DetailsPage.test.js
  src/Components/ResultPage/ResultPage.test.js
Labels: Testing

#79 Refactor design and display
  README.md
  src/Components/App/App.js
  src/Components/DetailPage/DetailsPage.js
  src/Components/DetailPage/DetailsPage.scss
  src/Components/Footer/Footer.js
  src/Components/Footer/Footer.scss
  src/Components/Footer/Footer.test.js
  src/Components/ResultPage/ResultPage.js
  src/Components/ResultPage/ResultPage.scss
Labels: design, fix bug

#82 Deploy and fix display of movie details
  src/Components/App/App.js
  src/Components/Form/Form.js
  src/Components/ResultPage/ResultPage.js
Labels: design, documentation

#84 Allow user to navigate to home and see correct results
  README.md
  src/Components/App/App.js
  src/Components/BrowsePage/BrowsePage.js
  src/Components/DetailPage/DetailsPage.js
  src/Components/ResultPage/ResultPage.js
Labels: UX, documentation, fix bug
